### ISSUE TITLE
Faltam arquivos no fonte

### ISSUE THREAD

**Issue by pedroluz89** [abacaxiguy/get_this_prices#1]
Fiz o clone aqui mas quando rodei o run.bat:

PS C:\Projects\get_this_prices> .\run.bat

C:\Projects\get_this_prices>cd ../../pythonbasico/venv/Scripts
The system cannot find the path specified.

C:\Projects\get_this_prices>call activate.bat
'activate.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\Projects\get_this_prices>cd ../../../myprojects/get_this_prices
The system cannot find the path specified.

C:\Projects\get_this_prices>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\Projects\get_this_prices>

**Comment by abacaxiguy** [comment]
Esse projeto foi primeiramente só feito para rodar na minha máquina, além de ser projetado somente para o site da https://www.kabum.com.br/ então os diretórios estão totalmente errados. Irei modificar e melhora-lo o mais rápido possível.

**Comment by abacaxiguy** [comment]
Os erros dessa issue já devem ter sido consertados com a última commit feita 🤝.
